name: CI - PySpark Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install pyspark nbconvert

      - name: Convert notebook to python (temp)
        run: |
          mkdir -p /tmp/nb
          jupyter nbconvert \
            --to python \
            src/notebooks/jobs/sensor_processing.ipynb \
            --output-dir /tmp/nb

      - name: Syntax check converted notebook
        run: |
          python -m py_compile /tmp/nb/sensor_processing.py

      - name: Cleanup
        run: |
          rm -rf /tmp/nb
